# Generated by Django 3.2 on 2021-08-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('published_date', models.PositiveIntegerField(default=0)),
                ('categories', models.TextField(null=True)),
                ('average_rating', models.FloatField()),
                ('ratings_count', models.PositiveIntegerField()),
                ('thumbnail', models.URLField()),
            ],
        ),
    ]
