# Generated by Django 3.2.6 on 2021-08-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
    ]
