# Generated by Django 3.2.6 on 2021-08-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210819_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
